// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-KaEkP1y-oBngKnSvLFOuUB622gq-FI',
    appId: '1:367068252268:android:7201fd33a9c72701b5b049',
    messagingSenderId: '367068252268',
    projectId: 'nursebinder',
    storageBucket: 'nursebinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-ryZUJzHslcsg0CK1Dti1mjcwmfdHzQ',
    appId: '1:367068252268:ios:c32d3c5432ae8d83b5b049',
    messagingSenderId: '367068252268',
    projectId: 'nursebinder',
    storageBucket: 'nursebinder.appspot.com',
    iosClientId: '367068252268-94gb7ehnu2sd2q1ipm1nb0jfk6kni4pn.apps.googleusercontent.com',
    iosBundleId: 'com.viral.nursebinder',
  );
}
